doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        # server_version: '15'
        logging: true
        profiling_collect_backtrace: '%kernel.debug%'

    orm:
        auto_generate_proxy_classes: false
        enable_lazy_ghost_objects: true
        report_fields_where_declared: true
        validate_xml_mapping: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                type: xml
                dir: '%kernel.project_dir%/config/doctrine/commerce' 
                prefix: 'App\Module\Commerce\Domain\Entity'
                alias: App
            Auth:
                is_bundle: false
                type: xml
                dir: '%kernel.project_dir%/config/doctrine/auth' 
                prefix: 'App\Module\Auth\Domain\Entity'
                alias: Auth

when@test:
    doctrine:
        dbal:
            url: "sqlite:///%kernel.project_dir%/var/app.db"

when@prod:
    doctrine:
        orm:
            auto_generate_proxy_classes: false
            proxy_dir: '%kernel.build_dir%/doctrine/orm/Proxies'
            query_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool

    framework:
        cache:
            pools:
                app.cache.redis:
                    adapter: cache.adapter.redis
                    provider: 'redis://redis:6379'


