services:
    php:
        build:
            context: ./docker/php
        restart: on-failure
        volumes:
            - ./:/var/www/html
            - ./vendor:/var/www/html/vendor
            - /var/lib/php/sessions:/var/lib/php/sessions
        depends_on:
            - mysql
            - redis

    nginx:
        image: nginx:1.27.2-alpine
        ports:
            - "80:80"
        restart: on-failure
        volumes:
            - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
            - /home/tomasz/projekty/php-projects/Epitaph:/var/www/html
        depends_on:
            - php

    mysql:
        image: mysql:8.0.33
        volumes:
            - mysql:/var/lib/mysql
            - ~/mysql_tmp:/tmp
        environment:
            MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
            MYSQL_DATABASE: "${MYSQL_DATABASE}"
            MYSQL_USER: "${MYSQL_USER}"
            MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
        ports:
            - "3306:3306"

    redis:
        build:
            context: ./docker/redis
        ports:
            - "6379:6379"
        volumes:
            - ./docker/redis/redis.conf:/usr/local/etc/redis/redis.conf
        command: ["redis-server", "/usr/local/etc/redis/redis.conf"]

volumes:
    mysql:
